services:
  client:
    image: aungkaungmoe/chatapp-client:latest
    container_name: chatclientapp
    ports:
      - "3000:3000"
    networks:
      - chat_network
    environment:
      - VITE_APP_BASE_IMAGE_URL=http://localhost:9000/
      - VITE_APP_BASE_URL=http://localhost:9000/api/

  server:
    image: aungkaungmoe/chatapp-server:latest
    container_name: chatserverapp
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    networks:
      - chat_network
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat-app
      - PORT=9000
      - ORIGIN=http://localhost:3000

  mongo:
    image: mongo:latest
    container_name: chat-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - chat_network

  nginx:
    image: nginx:alpine
    container_name: chat-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
    networks:
      - chat_network

volumes:
  mongo-data:

networks:
  chat_network:
    driver: bridge
